name: CI (build & push to ACR)

on:
  push:
    branches: 
    - "main"
  pull_request:

env:
  IMAGE_NAME: andreas-app

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Skapa en kort commit-SHA som tagg
      - name: Compute tag
        id: meta
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # Bygg image med två taggar: latest och commit-SHA
      - name: Build image
        run: |
          docker build -t ${{ secrets.ACR_URL }}/${{ env.IMAGE_NAME }}:latest \
                       -t ${{ secrets.ACR_URL }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.TAG }} .

      # Pusha båda taggarna till ACR
      - name: Push image
        run: |
          docker push ${{ secrets.ACR_URL }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ secrets.ACR_URL }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.TAG }}
